export default {
  CREATE_BUCKET: 'CREATE_BUCKET',
  DELETE_BUCKET: 'DELETE_BUCKET',
  INCREASE_QTY_BUCKET: 'INCREASE_QTY_BUCKET',
  REDUCE_QTY_BUCKET: 'REDUCE_QTY_BUCKET',
  CLEAR_BUCKET: 'CLEAR_BUCKET'
};
